version: 2.1

jobs:
  build:
    working_directory: ~/toolong
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Build files
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy:
    working_directory: ~/toolong
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Setup gh-pages
          command: |
            yarn add --dev gh-pages
            git config user.email "7994529+tcgj@users.noreply.github.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - '16:fc:be:10:25:e0:32:e3:12:c1:22:03:46:5e:7f:79'
      - run:
          name: Deploy to GitHub Pages
          command: yarn gh-pages --message "[skip ci] Redeployment" --dist dist

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
